config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  get 'movies/create'
  get 'movies/destroy'
  get 'movies/edit'
  get 'movies/update'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'users/index'
  get 'users/show'
  get 'users/new'
  get 'users/create'
  post 'users/update'
  get 'users/edit'
  get 'toppages/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :users, only: [:index, :show, :new, :create, :edit, :update]
  
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :liketo
      get :likefrom
    end
  end
  
  resources :movies, only: [:index, :create, :destroy, :edit, :update, :show]
  resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  mount_uploader :image_name, ImageNameUploader
  
  validates :title, presence: true, length: { maximum: 30 }
  validates :introduction, presence: true, length: { maximum: 500 }
  validates :category, presence: true
  
  has_many :favorites, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    mount_uploader :image_name, ImageNameUploader
    
    validates :name, presence: true, length: { maximum: 50 }
    validates :introduction, length: { maximum: 500 }
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                      uniqueness: { case_sensitive: false }
    
    has_secure_password                  
    has_many :movies
    
    has_many :favorites, dependent: :destroy
    has_many :liketo, through: :favorites, source: :movie
    has_many :reverses_of_favorite, class_name: 'Favorite', foreign_key: 'movie_id'
    has_many :likefrom, through: :reverses_of_favorite, source: :user
    
  def like(other_movie)
      self.favorites.find_or_create_by(movie_id: other_movie.id)
  end

  def unlike(other_movie)
    favorite = self.favorites.find_by(movie_id: other_movie.id)
    favorite.destroy if favorite
  end

  def alreadylike?(other_movie)
    self.liketo.include?(other_movie)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_movies = user.movies.count
    @count_liketo = user.liketo.count
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    movie = Movie.find(params[:movie_id])
    current_user.like(movie)
    flash[:success] = 'Movieをお気に入りに登録しました。'
    redirect_back(fallback_location: root_path)
  end

  def destroy
    movie = Movie.find(params[:movie_id])
    current_user.unlike(movie)
    flash[:success] = 'Movieのお気に入り登録を解除しました。'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  before_action :require_user_logged_in, only: [:index]
  before_action :correct_user, only: [:destroy, :edit]

  def index
    @movies_romance = Movie.where(category: "Romance").order(id: :desc).page(params[:page]).per(25)
    @movies_horror = Movie.where(category: "Horror").order(id: :desc).page(params[:page]).per(25)
    @movies_comedy = Movie.where(category: "Comedy").order(id: :desc).page(params[:page]).per(25)
    @movies_sf = Movie.where(category: "SF").order(id: :desc).page(params[:page]).per(25)
    @movies_musical = Movie.where(category: "Musical").order(id: :desc).page(params[:page]).per(25)
    @movies_animation = Movie.where(category: "Animation").order(id: :desc).page(params[:page]).per(25)
  end
  
  def show
    @movie = Movie.find(params[:id])
  end
  
  
  def create
    @movie = current_user.movies.build(movie_params)
    
    if @movie.save
      flash[:success] = 'Movieを投稿しました。'
      redirect_to root_url
    else
      @movies = current_user.movies.order(id: :desc).page(params[:page])
      flash.now[:danger] = 'Movieの投稿に失敗しました。'
      render 'toppages/index'
    end
  end

  def destroy
    @movie = current_user.movies.find(params[:id])
    @movie.destroy
    flash[:success] = 'Movieを削除しました。'
    redirect_back(fallback_location: root_path)
  end

  def edit
    @movie = current_user.movies.find(params[:id])
  end

  def update
    @movie = current_user.movies.find_by(id: params[:id])
    
    if @movie.update(movie_params)
      flash[:success] = 'Movieは正常に更新されました'
      redirect_to @movie.user
    else
      flash.now[:danger] = 'Movieは更新されませんでした'
      render :edit
    end
    
  end
  
  private
  

  def movie_params
    params.require(:movie).permit(:title, :category, :introduction, :image_name)
  end
  
  def correct_user
    @movie = current_user.movies.find_by(id: params[:id])
    unless @movie
      redirect_to root_url
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @movie = current_user.movies.build  # form_with 用
      @movies = current_user.movies.order(id: :desc).page(params[:page])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  before_action :correct_user, only: [:destroy]

  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @user = User.find(params[:id])
    @movies = @user.movies.order(id: :desc).page(params[:page])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to root_url
    end
  end
  
  def update
    @user = User.find_by(id: params[:id])
    
    if @user.update(user_params)
      flash[:success] = 'プロフィールは正常に更新されました'
      redirect_to @user
    else
      flash.now[:danger] = 'プロフィールは更新されませんでした'
      render :edit
    end
    
    if params[:image]
    @user.image_name = "#{@user.id}.jpg"  
    image = params[:image]
    File.binwrite("public/user_images/#{@user.image_name}", image.read)
    end
  end
  
  def liketo
    @user = User.find(params[:id])
    @movies = @user.liketo.page(params[:page])
    counts(@user)
    
  end
  

  private

  def user_params
    params.require(:user).permit(:name, :email, :image_name, :password, :password_confirmation, :introduction)
  end
  
  def correct_user
    @movie = current_user.movies.find_by(id: params[:id])
    unless @movie
      redirect_to root_url
    end
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_like_button.html.erb
<% if current_user.alreadylike?(movie) %>
<%= form_with(model: current_user.favorites.find_by(movie_id: movie.id), local: true, method: :delete) do |f| %>
  <%= hidden_field_tag :movie_id, movie.id %>
    <%= hidden_field_tag :movie_id, movie.id %>
    <%= button_tag :type => "submit", :class =>"btn btn-default btn-s-md" do %>
     <i class="fas fa-star fa-lg unlike"></i>
    <% end %>  
<% end %>
<% else %>
<%= form_with(model: current_user.favorites.build, local: true) do |f| %>
  <%= hidden_field_tag :movie_id, movie.id %>
    <%= button_tag :type => "submit", :class =>"btn btn-default btn-s-md" do %>
      <i class="far fa-star fa-lg like"></i>
    <% end %>
<% end %>
<% end %>

app/views/favorites/create.html.erb
<h1 class="movielist_category">Romance</h1>
<div style="text-align:center">
<%= render 'movies/movielist', movies: @movies_romance %>
</div>

<h1 class="movielist_category">Horror</h1>
<div style="text-align:center">
<%= render 'movies/movielist', movies: @movies_horror %>
</div>

<h1 class="movielist_category">Comedy</h1>
<div style="text-align:center">
<%= render 'movies/movielist', movies: @movies_comedy %>
</div>

<h1 class="movielist_category">Science Fiction</h1>
<div style="text-align:center">
<%= render 'movies/movielist', movies: @movies_sf %>
</div>

<h1 class="movielist_category">Musical</h1>
<div style="text-align:center">
<%= render 'movies/movielist', movies: @movies_musical %>
</div>

<h1 class="movielist_category">Animation</h1>
<div style="text-align:center">
<%= render 'movies/movielist', movies: @movies_animation %>
</div>

app/views/favorites/destroy.html.erb
<h1 class="movielist_category">Romance</h1>
<div style="text-align:center">
<%= render 'movies/movielist', movies: @movies_romance %>
</div>

<h1 class="movielist_category">Horror</h1>
<div style="text-align:center">
<%= render 'movies/movielist', movies: @movies_horror %>
</div>

<h1 class="movielist_category">Comedy</h1>
<div style="text-align:center">
<%= render 'movies/movielist', movies: @movies_comedy %>
</div>

<h1 class="movielist_category">Science Fiction</h1>
<div style="text-align:center">
<%= render 'movies/movielist', movies: @movies_sf %>
</div>

<h1 class="movielist_category">Musical</h1>
<div style="text-align:center">
<%= render 'movies/movielist', movies: @movies_musical %>
</div>

<h1 class="movielist_category">Animation</h1>
<div style="text-align:center">
<%= render 'movies/movielist', movies: @movies_animation %>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> flash"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Movie Collection</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to 'Movies', movies_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Users', users_path, class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Likes', liketo_user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
    
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Movie-collection</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Crimson+Text&display=swap" rel="stylesheet">
  </head>

  <body>
    
      <%= render 'layouts/navbar' %>

      <%= render 'layouts/flash_messages' %>
      
      <%= yield %>
      
  </body>
</html>

app/views/movies/_form.html.erb
<div class="kuuhaku"></div>
 <div class="edit_form">
    <h2>Edit Movie</h2>
      <%= form_with(model: movie, local: true) do |f| %>
      <% if movie.errors.any? %>
        <div id="error_explanation" class="alert alert-warning">
          <ul class="mb-0">
            <h3><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h3>
            <% movie.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      
    <div class="form-group">
      Movie Title: <%= f.text_area :title, class: 'form-control', rows: 1 %>
    </div>
    <div class="form-group">
      Movie Category: <%= f.select :category, [["Romance"], ["Horror"],  ["Comedy"], ["SF"],["Musical"],["Animation"] ],  :prompt => "Select" %>
    </div>
    <div class="form-group">
      Movie Intoroduction: <%= f.text_area :introduction, class: 'form-control', rows: 8 %>
    </div>
    
    <div class="form-group upload_wrap">
      <i class="fas fa-camera-retro"></i> Upload
      <p><%= f.file_field :image_name, :class => "upload_button"%></p>
    </div>
    
    <div class="edit_submit">
    <%= f.submit 'Post', class: 'btn btn-block post_button' %>
    </div>
    
    
    
  <% end %>
</div>

app/views/movies/_movie.html.erb
<div class="row kuuhaku">
  <aside class="col-sm-4">
  <div class="card">
    <div class="card-header">
      <h3 class="card-title"><%= @movie.title %></h3>
      </div>
      <div class="card-body">
        <% if @movie.image_name? %>
        <div class="user_image"><%= image_tag @movie.image_name.url%></div>
        <% else %>
         <div class="user_image"><img src="https://res.cloudinary.com/hbvvwh0vr/image/upload/v1570983763/noimage_k8cvmz"></div>
        <% end %>
          <div class="movie_title"><span class="movie_title_logo">User</span><%= movie.user.name %></div>
          <div class="movie_title"><span class="movie_title_logo">Category</span><%= movie.category %>
          <%= render 'favorites/like_button', movie: movie %>
          </div>
        </div>
      </div>
    </aside>
    
    <div class="col-sm-8">
      <h1 class="movielist_category">Introduction</h1>
      <h3><%= @movie.introduction %></h3>
    </div>

</div>

app/views/movies/_movielist.html.erb
<div class="kuuhaku">
  <ul class="list-unstyled">
  <% movies.each do |movie| %>
    <div class="user_list">
      <li class="media">
        <div class="media-body">
          <%= link_to movie_path(movie) do %>
          <% if movie.image_name? %>
            <div class="user_image"><%= image_tag movie.image_name.url %></div>
            <% else %>
             <div class="user_image"><img src="https://res.cloudinary.com/hbvvwh0vr/image/upload/v1570983763/noimage_k8cvmz"></div>
            <% end %>
          <% end %>
          <div class="movie_title"><span class="movie_title_logo">User</span><%= movie.user.name %></div>
          <div class="movie_title"><span class="movie_title_logo">Title</span><%= movie.title %>
          <%= render 'favorites/like_button', movie: movie %>
          </div>
          
        </div>
      </li>
    </div>
    <% end %>
  </ul>
</div>
<%= paginate movies %>

app/views/movies/_movies.html.erb
<ul class="list-unstyled">
  <% movies.each do |movie| %>
    <li class="media mb-3 movies_container">
      <div class="media-body">
        <div class="img_wrap hover_effect">
        <%= link_to movie_path(movie) do %>
          <% if movie.image_name? %>
            <div class="movie_image"><%= image_tag movie.image_name.url %></div>
          <% else %>
             <div class="movie_image"><img src="https://res.cloudinary.com/hbvvwh0vr/image/upload/v1570983763/noimage_k8cvmz"></div>
          <% end %>
        <% end %>
        </div>  
          <div class="movie_title"><span class="movie_title_logo">Title</span><%= movie.title %></div>
          <div class="movie_category"><span class="movie_category_logo">Category</span><%= movie.category %></div>
      </div>
        <ul class="list-unstyled">
            <li style="display:inline-block;"><%= render 'favorites/like_button', movie: movie %></li>
          <% if current_user == movie.user %>
            <li style="display:inline-block;"><%= link_to 'Edit', edit_movie_path(movie), class: 'btn btn-primary btn-sm' %></li>
            <li style="display:inline-block;"><%= link_to "Delete", movie, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %></li>
          <% end %>
        </ul>
    </li>
  <% end %>
  <%= paginate movies %>
</ul>

app/views/movies/_movies_forlike.html.erb
<ul class="list-unstyled">
  <% movies.each do |movie| %>
    <li class="media mb-3 movies_container">
      <div class="media-body">
        <div class="img_wrap hover_effect">
        <%= link_to movie_path(movie) do %>
          <% if movie.image_name? %>
            <div class="movie_image"><%= image_tag movie.image_name.url %></div>
          <% else %>
             <div class="movie_image"><img src="https://res.cloudinary.com/hbvvwh0vr/image/upload/v1570983763/noimage_k8cvmz"></div>
          <% end %>
        <% end %>
        </div>  
          <div class="movie_title"><span class="movie_title_logo">Title</span><%= movie.title %></div>
          <div class="movie_category"><span class="movie_category_logo">Category</span><%= movie.category %></div>
      </div>
        <ul class="list-unstyled">
            <li style="display:inline-block;"><%= render 'favorites/like_button', movie: movie %></li>
        </ul>
    </li>
  <% end %>
  <%= paginate movies %>
</ul>

app/views/movies/edit.html.erb
<%= render 'form', movie: @movie %>

app/views/movies/index.html.erb
<h1 class="movielist_category">Romance</h1>
<div style="text-align:center">
<%= render 'movielist', movies: @movies_romance %>
</div>

<h1 class="movielist_category">Horror</h1>
<div style="text-align:center">
<%= render 'movielist', movies: @movies_horror %>
</div>

<h1 class="movielist_category">Comedy</h1>
<div style="text-align:center">
<%= render 'movielist', movies: @movies_comedy %>
</div>

<h1 class="movielist_category">Science Fiction</h1>
<div style="text-align:center">
<%= render 'movielist', movies: @movies_sf %>
</div>

<h1 class="movielist_category">Musical</h1>
<div style="text-align:center">
<%= render 'movielist', movies: @movies_musical %>
</div>

<h1 class="movielist_category">Animation</h1>
<div style="text-align:center">
<%= render 'movielist', movies: @movies_animation %>
</div>

app/views/movies/show.html.erb
<div style="text-align:center">
<%= render 'movie', movie: @movie %>
</div>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <div class="row kuuhaku">
    <aside class="col-sm-4">
    <% if @movie.errors.any? %>
      <div id="error_explanation" class="alert alert-warning">
        <ul class="mb-0">
          <h3><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h3>
          <% @movie.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <h1 style="font-size: 30px">Let's Share Movies!</h1>
      <%= form_with(model: @movie, local: true) do |f| %>
        <div class="form-group">
          Movie Title: <%= f.text_area :title, class: 'form-control', rows: 1 %>
        </div>
        <div class="form-group">
          Movie Category: <%= f.select :category, [["Romance"], ["Horror"],  ["Comedy"], ["SF"],["Musical"],["Animation"] ],  :prompt => "Select" %>
        </div>
        <div class="form-group">
          Movie Intoroduction: <%= f.text_area :introduction, class: 'form-control', rows: 5 %>
        </div>
        <div class="form-group">
        <p><%=f.label "Upload Image:"%><br><span style="font-size:13px"><%= f.file_field :image_name %></span></p>
        </div>
        <%= f.submit 'Post', class: 'btn btn-primary btn-block post_button' %>
      <% end %>
    </aside>
    <div class="col-sm-8">
      <%= render 'movies/movies', movies: @movies %>
    </div>
  </div>
<% else %>
  <div class="center toppage_image">
    <div class="text-center-toppage">
      <h1>Movie Collection</h1>
      <h2>~ Let's Share Your Favorite Movies ~</h2>
      <%= link_to 'Sign up', signup_path, class: 'btn btn-lg top_button' %>
      <%= link_to 'Login', login_path, class: 'btn btn-lg top_button' %>
    </div>
  </div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
<div class="kuuhaku">
  <ul class="list-unstyled">
    <% users.each do |user| %>
    <div class="user_list">
      <li class="media" style="margin-bottom:10px">
        <div class="media-body">
          <div class="img_wrap">
            <%= link_to user_path(user) do %>
              <% if user.image_name? %>
                <div class="user_image"><%= image_tag user.image_name.url %></div>
              <% else %>
               <div class="user_image"><img src="https://res.cloudinary.com/hbvvwh0vr/image/upload/v1570983635/profile_zhxwvs.png"></div>
              <% end %>
            <% end %>
          </div>
          
            <p style="font-size:20px">User Name: <%= user.name %></p>
        </div>
      </li>
    </div>
    <% end %>
  </ul>
</div>
  <%= paginate users %>
<% end %>

app/views/users/edit.html.erb
<%= render 'form', user: @user %>
      

app/views/users/index.html.erb
<div style="text-align:center">
<%= render 'users', users: @users %>
</div>

app/views/users/liketo.html.erb
<div class="row kuuhaku">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <% if @user.image_name? %>
          <p class="user_image"><%= image_tag @user.image_name.url%></p>
        <% else %>
          <p class="user_image"><%= image_tag "/assets/profile.png"%></p>
        <% end %>
        <p class="user_introduction"><%= @user.introduction %></p>
      </div>
      <% if current_user == @user %>
      <%= link_to 'Edit Profile', edit_user_path(@user), class: 'btn btn-light edit_button' %>
      <% end %>
    </div>
  </aside>
  <div class="col-sm-8">
    <% if current_user == @user %>
    <div class="share_movie">
    <a class="btn btn-primary btn-block share_button" href="/">Share Movie?</a>
    </div>
    <%  end %>
    <br>
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">Movies  <span class="badge badge-secondary"><%= @count_movies %></span></a></li>
      <li class="nav-item"><a href="<%= liketo_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(liketo_user_path(@user)) %>">Likes  <span class="badge badge-secondary"><%= @count_liketo %></span></a></li>
    </ul>
    <%= render 'movies/movies_forlike', movies: @movies %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row kuuhaku">
  <aside class="col-sm-4">
  <div class="card">
    <div class="card-header">
      <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <% if @user.image_name? %>
        <div class="user_image"><%= image_tag @user.image_name.url%></div>
        <% else %>
         <div class="user_image"><img src="https://res.cloudinary.com/hbvvwh0vr/image/upload/v1570983635/profile_zhxwvs.png"></div>
        <% end %>
        <p class="user_introduction"><%= @user.introduction %></p>
        </div>
        <% if current_user == @user %>
        <%= link_to 'Edit Profile', edit_user_path(@user), class: 'btn btn-light edit_button' %>
        <% end %>
      </div>
    </aside>
    
    <div class="col-sm-8">
      <% if current_user == @user %>
      <div class="share_movie">
      <a class="btn btn-block share_button" href="/">Share Movie?</a>
      </div>
      <%  end %>
      <br>
      <ul class="nav nav-tabs nav-justified mb-3">
        <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">Movies <span class="badge badge-secondary"> <%= @count_movies %> </span></a></li>
        <li class="nav-item"><a href="<%= liketo_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(liketo_user_path(@user)) %>">Likes <span class="badge badge-secondary"><%= @count_liketo %></span></a></li>
      </ul>
  
      <%= render 'movies/movies', movies: @movies %>
    
  </div>

</div>